### ISSUE TITLE
Are earlier versions available?

### ISSUE THREAD

**Issue by dewib** [swannman/pdf2gerb#2]
I can't get the current version to work with the digit board on osx or strawberry perl and I want to try the Illustrator workflow. Thanks.

**Comment by dewib** [comment]
Gave ubuntu a shot for good measure. The supplied digit board copy.pdf does the Modification of non-creatable array thing... line 1244 and files saved from the ai version as v1.3 pdf, with no text/line compression, kick out line 349 issues with sprintf including invalid conversions missing arguments and finally integer overflow.

**Comment by djulien** [comment]
Which version of Strawberry Perl is this happening with?

**Comment by dewib** [comment]
Of course, I'll try git, thanks. Strawberry 50.20.2.1 32 bit.

**Comment by djulien** [comment]
closing old issue.  please re-open if it's still a problem.
