### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Mooseloser** [swannman/pdf2gerb#3]
Version 1.6j flat out doesn't work, either with the presupplied demo files or my own PDFs.
I found an older version 1.6e, which works flawlessly.

Running StrawberryPerl 5.22.1.1-64bit on Windows 7.

**Comment by djulien** [comment]
Please try latest version.  I corrected a mistake introduced after version 1.6e.

**Comment by Mooseloser** [comment]
It works! Thank you!
