### ISSUE TITLE
Can't locate pdf2gerb_cfg.pm

### ISSUE THREAD

**Issue by lycoch** [swannman/pdf2gerb#4]
hello,

cat /etc/debian_version 
buster/sid
perl -v
This is perl 5, version 26, subversion 1 (v5.26.1)

./pdf2gerb.pl 
Can't locate pdf2gerb_cfg.pm in @INC (you may need to install the pdf2gerb_cfg module) (@INC contains: . /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./pdf2gerb.pl line 168.
BEGIN failed--compilation aborted at ./pdf2gerb.pl line 168.

how can i fix this issue ?
thanks

**Comment by djulien** [comment]
Hi Jerry,

Is there a pdf2gerb_cfg.pm file in the same folder as pdf2gerb.pl?

One of the changes in the last release was to move configurable parameters out to a separate file so they can vary by project.  It is supposed to look for that file in the current folder or the folder where pdf2gerb.pl exists.

don

**Comment by djulien** [comment]
Can this issue be closed?

**Comment by lycoch** [comment]
yes please
now i can launch the software
i still cannot get something from my simple pdf but i guess it is another story ...

**Comment by djulien** [comment]
okay.  Pls post or open another issue if you are still having problems with it.
